### ISSUE TITLE
idea: Club Advertisements

### ISSUE THREAD

**Issue by aw-0** [stevenson-space/shs#141]
Have users submit club advertisements via a GForm and have them be featured on the front page based on a time/date, similar to Girls Who Code/SHSHacks ads

**Comment by JosephShepin** [comment]
Note to this would be that they are related to cs/engineering opportunities like we have done in the past such as hackathons and cs clubs. I think we don’t want an open advertising policy as it would likely become yet another place where people see the same ad they have seen everywhere else.

**Comment by Oreo-Silk** [comment]
We can also design it in a way to submit the advertisement for clubs first to be approval by the stevenson.space team, and then published by the team itself.
