### ISSUE TITLE
Idea: Report a problem 

### ISSUE THREAD

**Issue by JosephShepin** [stevenson-space/shs#142]
Allow users to flag an issue with lunch, schedules or other. A SASS app may be chosen. A written cloud-architected solution is also possible - netlify functions are likely in this equation. Solution must be free.

**Comment by aw-0** [comment]
This coincides with another feature that I was working on a little while ago, probably mentioned in DMs ([looks like it](https://discord.com/channels/@me/975071434709815367/995871388906823810)), an SS feedback form. We could add a little flag icon next to lunches & schedules that could lead to that form? Think the original feedback feature can be merged into this as well.

**Comment by aw-0** [comment]
Started work on this issue - about 90% done! I'd like to add this to lunch, but I can't access it as there's no lunch data 🙃 

Available @ https://github.com/aw-0/shs/tree/feedback-form

**Comment by aw-0** [comment]
@JosephShepin Should we close?

**Comment by JosephShepin** [comment]
yes. one nice thing is that if an issue is linked with the PR. it will close automatically when merged.
