### ISSUE TITLE
Bandwidth usage

### ISSUE THREAD

**Issue by Chaldron** [stevenson-space/shs#217]
Looks we just went over the bandwidth limit for February by ~10 GB, which results in Netlify automatically billing us for a 100 GB add-on pack. Some questions:

1. Do we have any visibility on how bandwidth is being used, maybe through Sentry or some other source? The free tier does not include analytics unfortunately.
2. Should we look into putting the site (or maybe just media assets) behind Cloudflare / another CDN? The other option is to upgrade to Netlify Pro for $20/month but it seems kind of costly since we're still barely pushing any bandwidth.

**Comment by JosephShepin** [comment]
We went over 100GB for the month?!

**Comment by Chaldron** [comment]
Unfortunately Netlify does not provide historical bandwidth usage unless you use their analytics service. I received an email several months ago with a warning that we'd hit 90% usage but it was very close to the end of the month. I think this is the first time we've gone over the cap.

<img width="1072" alt="image" src="https://github.com/stevenson-space/shs/assets/3259988/c149ba94-0835-442b-8eed-02c378ea501a">

**Comment by JosephShepin** [comment]
that's unfortunate. I'm almost sure the culprit is the images. @aw-0 and I let this one slip by, but the shshacks image a contributor gave us is 8MB holy moly 🤦🏻 . Based on my calculations we shouldn't be getting anywhere near 100GB of bandwidth without the images being loaded (for the themes) so we can move those over to something like contentful which has a 1TB bandwidth limit.

**Comment by aw-0** [comment]
That's crazy.. wish they had some more observability for what's using the most bandwidth

The solution could just be putting the entire site behind Cloudflare. Their free tier is really generous and they automatically cache almost everything at the CF proxy level which speeds up the site as well.

E.x. For another site I run, even though it has a lot less traffic almost all of it is cached through CF
![image](https://github.com/stevenson-space/shs/assets/43796708/73b1f527-3283-41a1-95a5-b1f230f13c4e)

We could also stick all the images behind a cdn but cloudflare would be a much faster fix haha

**Comment by JosephShepin** [comment]
@aw-0 do you know if we will be billed for our amount of cloudflare usage if we used it?

**Comment by JosephShepin** [comment]
we should try to get something done in the next few days so we don't run into this issue during March.

**Comment by aw-0** [comment]
@JosephShepin Cloudflare's CDN (and ddos protection) is completely free for proxied sites, so we shouldn't run into any roadblocks there. They seem to only charge for nice-to-have features (no code stuff) & enterprises.

I can set some time aside this week to work on the conversion if needed. Only issue is I'm not sure if Netlify's CDN will conflict with Cloudflare, as I've ran into that same issue with vercel. We could potentially [migrate to Cloudflare Pages](https://developers.cloudflare.com/pages/migrations/migrating-from-netlify/) to account for this, but that's a pretty big move.

Upside is Cloudflare Pages has no bandwidth/request limit, and is priced on concurrent builds and # of builds/month (500). More [here](https://www.cloudflare.com/plans/developer-platform/)

**Comment by aw-0** [comment]
We also ran https://shsgiveathon.com entirely on Cloudflare Pages this year, and while it obv didn't have the same high traffic lol, we didn't have to micromanage it or anything.

**Comment by JosephShepin** [comment]
ok cool, i'll look into this as well. The main downside of using cloudflare pages is we would have to rework some of our routing/networking stuff that we have in netlify.toml and our form submissions for the textbook that are done with a plugin from netlify. I think we would like to avoid having to move to cloudflare but we can see.

**Comment by aw-0** [comment]
Ahhh I forgot about those, yea that'd make it a lot harder to switch. I googled a bit and looks like Netlify really discourages (and not even sure if they support) [putting websites behind Cloudflare as it conflicts with their own cdn](https://answers.netlify.com/t/support-guide-why-not-proxy-to-netlify/8869). Funny considering they also want to charge $50 for 100gb out when CF is free lmao

Not really sure what else we could do other than try and compress the images as much as possible. Maybe taking a look at the network tab could help on response sizes as well.

**Comment by JosephShepin** [comment]
ok I see two possible options: 

#1. We move all the theme images to contentful which are relatively large instead of having the them hardcoded which would hopefully reduce the bandwidth.

#2. move to cloudflare pages (from netlify), and write a serverless function to handle form submissions via email.


@Chaldron

**Comment by aw-0** [comment]
[(which you can send/receive emails for free through those functions)](https://blog.cloudflare.com/sending-email-from-workers-with-mailchannels)

**Comment by Chaldron** [comment]
Lots of good ideas, I also ran into the same forum posts stating that Netlify isn't designed to be put behind Cloudflare but there were a couple of guides online on how to do it. But more importantly I really dislike that there is no way to put a bandwidth/billing cap on Netlify, and they will continue to serve the site no matter what even if you're racking up a ton of costs. [This was just in the news today, for example.](https://old.reddit.com/r/webdev/comments/1b14bty/netlify_just_sent_me_a_104k_bill_for_a_simple/) I like Netlify as a platform but it is a bit worrisome that we have no way to ensure our bill doesn't get blown up, especially at these absurd prices.

Other than the submission form and the redirects, do we rely on Netlify for anything else? Looks like Cloudflare can handle both the email and [redirects](https://developers.cloudflare.com/pages/configuration/redirects/), so I'm not opposed to switching. It would definitely be quite a bit of work though, so any other ideas are welcome as well. 

We already have a CF account for hosting some assets right?

**Comment by JosephShepin** [comment]
> We already have a CF account for hosting some assets right?

yes we have a cloudflare account already

**Comment by aw-0** [comment]
Imo this is the best option. I like the idea of putting images behind a different cdn, but that would probably increase development complexity, especially when I hand this off to another student after next year.

More than happy to start putting together a PR for this if yall would like - sure you're busy.

This'll work out well as we already use Cloudflare Functions for Jukebox 🙃

**Comment by Chaldron** [comment]
That would be really great, thanks - always too busy with work 😅 

In the meantime I'll keep an eye on the bandwidth usage, we're now at 117 so maybe we should compress some assets just to be safe for March.

**Comment by aw-0** [comment]
@Chaldron @JosephShepin looks like Github sent a request to let me add this repo to Cloudflare Pages to build & deploy. Also - to get the full benefits of Cloudflare, we'd prob need to move DNS over to it at some point as well. Obviously not something I can do but thought I'd give a heads up

**Comment by JosephShepin** [comment]
Yeah Aditya can approve the access for that. Once the site looks good on cloudflare, he should be able to move it over to CF

**Comment by Chaldron** [comment]
I approved it yesterday but didn't have the Cloudflare login to check if it worked on the other side, let me know if it's not working

<img width="661" alt="image" src="https://github.com/stevenson-space/shs/assets/3259988/e7786d94-d08b-480d-90c7-010428e5f1aa">

**Comment by JosephShepin** [comment]
@Chaldron you can check Gitter, the login for CloudFlare are posted there

**Comment by aw-0** [comment]
looks like there's another request heading your way for this repo... haha

![Arc Screenshot 2024-03-01 at 10 46 32@2x](https://github.com/stevenson-space/shs/assets/43796708/cca1167a-bd01-4bb2-b5fb-f0de2a3d06bb)

Played around with Cloudflare pages on my fork and it works pretty well out of the box. Only issue is that they [don't support redirect proxying to external domains](https://developers.cloudflare.com/pages/configuration/redirects/#proxying), so sending/receiving configs will need to be changed to the URLs we proxy to. Not sure the upside/downside to that as I've never touched that feature

**Comment by abhinavpappu** [comment]
Looking at the commit history a bit, I think I originally proxied that URL since it didn't support https at the time which caused some problem. But actually looks like we already switched to https in the netlify.toml redirects 2 years ago, so I don't anticipate any issues with just using the dpaste.com url directly in Transfer.vue.

(also even if it doesn't work for some reason, i doubt anyone uses the transfer settings feature anyway, so shouldn't be blocker for switching to cloudflare)

**Comment by Chaldron** [comment]
Got an email about switching our DNS name server to Cloudflare, are we ready for the switch already?

**Comment by JosephShepin** [comment]
> Got an email about switching our DNS name server to Cloudflare, are we ready for the switch already?

we're not gonna switch yet. you can ignore that as of right now.
