### ISSUE TITLE
Idea: Make the theme change color depending on time remaining

### ISSUE THREAD

**Issue by Jleibovitz** [stevenson-space/shs#218]
One effective way to visually represent the duration of a particular task or event is by using a gradient. This involves starting with a specific color and then gradually fading into another color as time elapses. This method provides a clear and intuitive visual representation of how much time remains in the period.

Alternatively, there are various other visual timers that one can use to enhance time management. For example, you can find numerous creative and innovative timer designs on YouTube that incorporate visual cues to help users stay on track and manage their time more effectively.

**Comment by aw-0** [comment]
Hey there! Congrats on your first issue on Github. This sounds like an interesting idea, but it looks like your description is written entirely with GPT. We'd appreciate if you could explain what you were thinking using your own words.
