### ISSUE TITLE
Underline on iPad Chrome is blue

### ISSUE THREAD

**Issue by JosephShepin** [stevenson-space/shs#225]
![image](https://github.com/user-attachments/assets/591c1ac3-fec8-4bf4-aa64-da8c4bddf0ed)

We want the underline color for the text on the weather card to be the primary color used by the theme, it is currently blue.

**Comment by aw-0** [comment]
fixed in latest commit - thx for the catch!

**Comment by JosephShepin** [comment]
Thanks for this @aw-0
