### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Chaldron** [stevenson-space/shs#70]
I think we should add some type of license to the repo. I'm thinking MIT/BSD are too open and would allow versions that are not open-source, so we should go for GPL 3 in the spirit of open source. What do you guys think? @abhinavpappu @jshepin

**Comment by jshepin** [comment]
I'm not legal expert, but that sounds good.

**Comment by jshepin** [comment]
Definitely like the idea of restricting it to only be an open source.

**Comment by abhinavpappu** [comment]
Yep sounds good!
