### ISSUE TITLE
fix prebuild scripts

### ISSUE THREAD

**Issue by jshepin** [stevenson-space/shs#73]
Hi, just made a commit, and the lunch.json isn't right compared to what I have locally after running lunch.json manually. I believe the lunch.js isn't running. Any thoughts? Thanks

On august 12 the lunch should be: 
![Screen Shot 2021-08-05 at 7 20 01 PM](https://user-images.githubusercontent.com/31457361/128437365-e653c054-9d17-402d-aba2-d7d0a4d4fc30.png)
Prod. is correct when it matches that pic.

**Comment by jshepin** [comment]
We forgot to move it over in `package.json` when we switched to vue-cli. I Added it now.

**Comment by jshepin** [comment]
still see no change. This might be on the netlify end of things to fix.

**Comment by abhinavpappu** [comment]
Good catch with the pre-build script! That actually did fix the issue, but looks like there's another one that's causing the build to fail:  https://app.netlify.com/sites/shs/deploys/610c827eb10d860007df2aea. I think I accidentally removed `cheerio` as a dev dependency when migrating to `vue-cli`, will add it back now

**Comment by abhinavpappu** [comment]
Fixed by 3c28537c01de66e678e2e2e0624bc34cbaa034df. Still running into a few other issues: #74 and another [build error](https://app.netlify.com/sites/shs/deploys/610cc4dba4c0740008d01e02) (looks related to typescript at first glance), but I think this issue can be closed
